[package]
name = "pumpkin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.rel-with-debug]
inherits = "release"
debug = true

[dev-dependencies]
rand = "0.8.5"
